language: node_js
node_js:
- 10.1.0
cache:
  yarn: true
script:
- docker-compose up -d
- while ! $(curl --silent --fail --output /dev/null http://localhost:8080/); do sleep
  1; done
- "./fixture/purge.sh"
- "./fixture/import.sh"
- yarn install
- yarn gatsby build --prefix-paths
- touch public/.nojekyll
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  local-dir: "./public"
  keep-history: false
  skip-cleanup: true
  target-branch: gh-pages
  on:
    branch: master
env:
  global:
    secure: XCqYMdqGPDkZHc+cidb1WBZnJ0YcD0nyRwfMqESy0Z1kHOCACqlhVlB5HtKO+H8RqFDLzcAgoNgtMpCgSZoczyi7R2rfkWpo1nC7gDf9SmGWun8LCRA9gY2ksTztZnbQPrunL+bqqiZQqzYpPCzYlR3oZrwIU3Nz/JmdSpXi/mcCt0YMKPRkIF+ALtQhxDtcWbmaG+yWpA7wWInEu4L0b+gzcL4eQkjvhkRV7Vrn03G/vB0xhlmeeb/1uH2OmmMC+/iooK+op7N/ZQiUaZuNwow+6Z/9wt06j+zDzTtzdW9Sjm5KnuLXCJJa8HJ7uQBNdrU3MqSNa1F6fPJNPV3HNKGqghtNPDa6YC2Zy3WGR2+T/65w98tvF6jSTTdWZYQe7lT0wXlnzRZUwXiWzAJdj0Uepcq6aVTfB4sL7CuozckYVbCWojCzVm9pxP5+LTpIDftRbDtJNFpQBcD/ufAKc0BvBT6Wdi1TJ04vwbo2zpAH+iqBs/MjbYpc1Whz0uZgk6LzdRYZSQBSCGqIzOwgYzCSsftkGqIoJen1BToGIND6X4CHSZ0jXD203FdBxSmjc3DYB42ZnGWlapimt2kAWNkHCcKlF3rPu8WEPR7tWVxz5yc5vcXJmcu+B9NXUZs8ijaxQtuxXkAEzjOOLkXhlZfopBcfgf65xBRGpQYWtNI=
